
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    apiUrl: 'https://localhost:5001/',
    clientId: 'YOUR_CLIENT_ID_FROM_AUTH0',
    audience: 'YOUR_API_URL',
    redirectUrl: 'URL_TO_BE_REDIRECTED_AFTER_SUCCESS_LOGIN',
    scope: 'YOUR_API_SCOPES',
    domain: 'AUTH0_TENANT_DOMAIN',
  };
